# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ManualAwsSigningExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'CryptoSwift'
  pod 'AWSMobileClient'

  # Pods for ManualAwsSigningExample

  target 'ManualAwsSigningExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
